### ISSUE TITLE
(Major Suggestion) Area Status Viewer

### ISSUE THREAD

**Issue by lupadim** [AttorneyOnlineVidya/serverD#10]
Integrate /area with details on what the areas are currently doing. Allow five statuses: 
IDLE
BUILDING (OPEN ROLES)
BUILDING (FULL)
CASING (OPEN ROLES)
CASING (FULL)

And allow players to change the status with a command, such as /setstatus buildingf

**Comment by lupadim** [comment]
Bonus: Also allow for, if casing, set the current point of the trial, such as "START", "DETECTIVE", "WITNESS 1", "WITNESS 2", "VERDICT", "POST-TRIAL"

**Comment by Lewdton** [comment]
Done
