### ISSUE TITLE
/change feedback

### ISSUE THREAD

**Issue by lupadim** [AttorneyOnlineVidya/serverD#2]
Currently, when /change fails it is impossible to tell if it's because the character you aimed for is already taken, or if it's because you made a typo when typing the targeted character's name. It'd be useful to see the command return some message to notify the user on what happened.

Example

I use /change Barok but Barok is already taken
SYSTEM: Impossible to switch because Barok is already taken.

I use /change Barrok
SYSTEM: Impossible to switch because there is no Barrok on the character list

**Comment by Lewdton** [comment]
Done
