### ISSUE TITLE
A "fetch doc" command

### ISSUE THREAD

**Issue by lupadim** [AttorneyOnlineVidya/serverD#9]
Allow players to use the command /maindoc to fetch the doc that others are currently using.

Allow, of course, another command that enables them to set what is the current active doc.

In order to avoid abuse, make it so that changes into the active doc are shown to everyone in the OOC. Example:
Hawk changed the current active doc to "(link)"

And make it so that changing the active doc to something other than what is currently being used during cases is an offense to Rule 2.

**Comment by Lewdton** [comment]
Done
